# Generated by Django 4.1.3 on 2022-12-08 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comprobante',
        ),
        migrations.DeleteModel(
            name='Costo',
        ),
        migrations.DeleteModel(
            name='Queja',
        ),
        migrations.DeleteModel(
            name='Venta',
        ),
    ]
